server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbt
    username: root
    password: rh3dlekx123@
    #security:
    #user:
    #name: user
    #password: 12345
  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: redis
    port: 6379
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

  # Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이 ant_apth_matcher에서 path_pattern_parser로 변경되면서 몇몇 라이브러리(swagger포함)에 오류
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



test:
  api-version: 0.0.1
  access-hold-time: 10
  access-hold-time-millis: 10000

